baseURL = "https://www.carlolobrano.com/"
languageCode = "en-us"
title = "Works for me"
theme = "hugo-coder"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
title = "Works for me"
author = "Carlo Lobrano"
info = "Stories and ideas on SW development and smart tools"
avatarurl = "img/pic.jpg"

hidecredits = false
hidecopyright = false

rtl = false
math = true
custom_css = []

## Social links
[[params.social]]
icon = "fab fa-linkedin fa-2x"
title = "Linkedin"
weight = 1
url = "https://www.linkedin.com/in/carlolobrano/"

[[params.social]]
icon = "fab fa-github fa-2x"
title = "GitHub"
weight = 2
url = "https://github.com/clobrano"

[[params.social]]
icon = "fab fa-twitter fa-2x"
title = "twitter"
weight = 3
url = "https://twitter.com/carlolobrano"

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/posts/"

[[menu.main]]
name = "About"
weight = 300
identifier = "about"
url = "/about/"
