baseURL = "https://blog.carlolobrano.com/"
languageCode = "en-us"
title = "IT works, for me."
theme = "PaperMod"
summarylength = 10
enableEmoji = true
enableRobotsTXT = true

paginate = 20
canonifyurls = true

pygmentsstyle = "bw"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

[params]
title = "IT works, for me."
author = "Carlo Lobrano"
description = "Blog about Linux, Open Source and Software development"
avatarurl = "img/pic.jpg"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowRssButtonInSectionTermList = true
ShowToc = true
hidecredits = false
hidecopyright = false

rtl = false
math = true
custom_css = []

[params.homeInfoParams]
Title = "Hi, Carlo Lobrano here 👋"
Content = """
I'm an Italian Software Engineer and Open source enthusiast.
- 💻 My daily job is on Embedded software, using mostly C/C++, but...
- 🔧 I like to develop software in other languages too ([Python](https://github.com/clobrano/letsdo), [Golang](https://github.com/clobrano/sendat), and [Bash](https://github.com/clobrano/script-fu)).
"""

[params.plausibleAnalytics]
domain = "blog.carlolobrano.com"
# Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
#serverURL = "analytics.example.com"

## Social links
[[params.socialIcons]]
name = "Github"
icon = "fa fa-2x fa-github"
weight = 1
url = "https://github.com/clobrano"

[[params.socialIcons]]
name = "LinkedIn"
icon = "fa fa-2x fa-linkedin"
weight = 4
url = "https://www.linkedin.com/in/carlolobrano/"

[[params.socialIcons]]
name = "Twitter"
icon = "fa fa-2x fa-twitter"
weight = 3
url = "https://twitter.com/carlolobrano"

[[menu.main]]
name = "Home"
identifier = "home"
weight = 100
url = "/"

[[menu.main]]
name = "Posts"
weight = 200
identifier = "posts"
url = "/posts/"

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4
